FROM polimi/rubis-jboss

MAINTAINER Giovanni Quattrocchi <giovanni.quattrocchi@polimi.it>

EXPOSE 8080

CMD ["/opt/jboss-4.2.2.GA/bin/run.sh", "--host", "0.0.0.0", "--bootdir", "/opt/rubis/rubis-cvs-2008-02-25/Servlets_Hibernate"]

/opt/jboss-4.2.2.GA/bin/run.sh --host 0.0.0.0 --bootdir /opt/rubis/rubis-cvs-2008-02-25/Servlets_Hibernate